/** Auto-generated by scripts/sync-render-variants.mjs — do not edit. */

export const RENDER_VARIANT_SLUGS = [
  'opus-4.8-high',
  'opus-4.8-max-mistake',
  'opus-4.8-max',
  'chatgpt-5.5',
  'chatgpt-5.5-two',
  'chatgpt-5.5-three',
  'mix-opus-composer',
  'opus-4.8-max-two',
  'composer-2-max',
] as const;

export type RenderVariantSlug = (typeof RENDER_VARIANT_SLUGS)[number];

export type RenderVariantDef = {
  slug: RenderVariantSlug;
  label: string;
  gitBranch: string;
  /** Canonical showcase save for this branch pipeline. */
  saveId: number;
  /** All built-in save ids shipped on this branch. */
  saveIds: number[];
};

export const RENDER_VARIANTS: RenderVariantDef[] = [
  { slug: 'opus-4.8-high', label: "Opus 4.8 High", gitBranch: 'claude-opus-4.8-high-experiment-five-attempt', saveId: 22, saveIds: [20, 21, 22] },
  { slug: 'opus-4.8-max-mistake', label: "Opus 4.8 Max (mistake)", gitBranch: 'claude-opus-4.8-max-experiment-five-attempt-mistake', saveId: 29, saveIds: [20, 21, 22, 29] },
  { slug: 'opus-4.8-max', label: "Opus 4.8 Max", gitBranch: 'claude-opus-4.8-max-experiment-five-attempt', saveId: 32, saveIds: [20, 21, 22, 29, 31, 32] },
  { slug: 'chatgpt-5.5', label: "ChatGPT 5.5 veryhigh", gitBranch: 'chatgpt-5.5-veryhigh-experiment-five-attempt', saveId: 45, saveIds: [20, 21, 22, 44, 45] },
  { slug: 'chatgpt-5.5-two', label: "ChatGPT 5.5 2", gitBranch: 'chatgpt-5.5-2-experiment-ten-white-pane-attempt', saveId: 201, saveIds: [201] },
  { slug: 'chatgpt-5.5-three', label: "ChatGPT 5.5 3", gitBranch: 'chatgpt-5.5-3-experiment-ten-white-pane-attempt', saveId: 223, saveIds: [219, 223, 226] },
  { slug: 'mix-opus-composer', label: "Mix · Opus 4.8 + Composer 2.5", gitBranch: 'mix-claude-opus-4.8-max-composer-2.5-experiment-five-attempt', saveId: 55, saveIds: [20, 21, 22, 54, 55] },
  { slug: 'opus-4.8-max-two', label: "Opus 4.8 Max (two)", gitBranch: 'claude-opus-4.8-max-experiment-five-attempt-two', saveId: 66, saveIds: [20, 21, 22, 54, 66] },
  { slug: 'composer-2-max', label: "Composer 2 Max", gitBranch: 'composer-2-max-experiment-five-attempt-two', saveId: 76, saveIds: [20, 21, 22, 74, 76] },
];

const showcaseSaveIds = new Set<number>(RENDER_VARIANTS.map((v) => v.saveId));

export function renderVariantForSaveId(
  saveId: number,
  branchSlug?: RenderVariantSlug,
): RenderVariantDef | undefined {
  if (branchSlug) {
    return RENDER_VARIANTS.find((v) => v.slug === branchSlug && v.saveIds.includes(saveId));
  }
  const matches = RENDER_VARIANTS.filter((v) => v.saveIds.includes(saveId));
  return matches.length === 1 ? matches[0] : undefined;
}

export function isBranchShowcaseSaveId(saveId: number): boolean {
  return showcaseSaveIds.has(saveId);
}
